#ifndef KCVERIFY_EOEN_DATABASE_KANCOLLE_API_META_HPP_INCLUDED
#define KCVERIFY_EOEN_DATABASE_KANCOLLE_API_META_HPP_INCLUDED

#include "eoen/database/kancolle_api/meta/api_files.hpp"

#endif  // KCVERIFY_EOEN_DATABASE_KANCOLLE_API_META_HPP_INCLUDED
